import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { createRequire } from "node:module";
import { mkdir, copyFile, chmod } from "node:fs/promises";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const require = createRequire(import.meta.url);

async function copyVendoredExiftool() {
	try {
		const src = require.resolve("exiftool-vendored.pl/bin/exiftool");
		const dstDir = path.join(process.cwd(), "vendor");
		const dst = path.join(dstDir, "exiftool");
		await mkdir(dstDir, { recursive: true });
		await copyFile(src, dst);
		await chmod(dst, 0o755);
		console.log("[build] copied vendored exiftool -> vendor/exiftool");
	} catch (e) {
		console.warn("[build] failed to copy vendored exiftool:", e);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await copyVendoredExiftool();
	process.exit(0);
} else {
	await copyVendoredExiftool();
	await context.watch();
}
